# Generated by Django 6.0.6 on 2026-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('edrpou', models.CharField(blank=True, max_length=20, verbose_name='ЄДРПОУ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Організація',
                'verbose_name_plural': 'Організації',
            },
        ),
    ]
