# Generated by Django 6.0.6 on 2026-07-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва уроку')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('content', models.TextField(blank=True, verbose_name='Текст уроку')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], default='draft', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order', 'title'],
            },
        ),
    ]
